Assessment/Controllers/EmpDetailsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SampleProject.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace SampleProject.Controllers
{
    public class EmpDetailsController : Controller
    {
        // GET: EmpDetailsController

        SqlConnection con = new SqlConnection("Server = DESKTOP-OK1P17M\\MSSQLSERVERNEW; Database = EmployeeDB; integrated security =True");

        public ActionResult ListEmployeeDetails()
        {
            DataTable dt = new DataTable();
            using (con)
            {
                con.Open();
                SqlCommand cmd = new SqlCommand("SP_ListEmployeeDetail", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                sda.Fill(dt);

            }
            return View(dt);
        }
        [HttpGet]
        //public ActionResult ParticularEmp(int id)
        //{
        //    DataTable dt = new DataTable();
        //    using (con)
        //    {
        //        con.Open();
        //        SqlCommand cmd = new SqlCommand("Particular", con);
        //        cmd.Parameters.AddWithValue("Empid", id);
        //        cmd.CommandType = CommandType.StoredProcedure;
        //        SqlDataAdapter sda = new SqlDataAdapter(cmd);
        //        sda.Fill(dt);

        //    }
        //    return View();
        //}


        //public ActionResult NETSAL()
        //{
        //    using (con)
        //    {

        //        con.Open();
        //        SqlCommand cmd = new SqlCommand("SP_CreateEmpDetail", con);
        //        cmd.CommandType = CommandType.StoredProcedure;
        //        SqlDataAdapter sda = new SqlDataAdapter(cmd);



        //        return View();
        // }



        // GET: EmpDetailsController/Details/5


        // GET: EmpDetailsController/Create
        public ActionResult CreateEmployeeDetail()
        {
            return View(new EmployeeDetail());
        }

        // POST: EmpDetailsController/Create
        [HttpPost]

        public ActionResult CreateEmployeeDetail(EmployeeDetail ed)
        {
            DataTable dt = new DataTable();
            using (con)
            {

                con.Open();
                SqlCommand cmd = new SqlCommand("SP_CreateEmpDetail", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);

                cmd.Parameters.AddWithValue("Empid", ed.Empid);
                cmd.Parameters.AddWithValue("@DateOfBirth", ed.DateOfBirth);
                cmd.Parameters.AddWithValue("@DateOfJoining", ed.DateOfJoining);
                cmd.Parameters.AddWithValue("@Designation", ed.Designation);
                cmd.Parameters.AddWithValue("@Degree", ed.Degree);
                cmd.Parameters.AddWithValue("@PassOutYear", ed.PassOutYear);
               

                cmd.ExecuteNonQuery();
                sda.Fill(dt);

            }
            return RedirectToAction("ListEmployeeDetails");
        }









       
        public ActionResult EditEMpDetail(int id)
        {
            return View(new EmployeeDetail());
        }

        // POST: EmpDetailsController/Edit/5
        [HttpPost]
      
        public ActionResult EditEmpDetail(EmployeeDetail ed)
        {
            DataTable dt = new DataTable();
            using (con)
            {

                con.Open();
                SqlCommand cmd = new SqlCommand("SP_EditEmpDetails", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);

                cmd.Parameters.AddWithValue("Empid", ed.Empid);
                cmd.Parameters.AddWithValue("@DateOfBirth", ed.DateOfBirth);
                cmd.Parameters.AddWithValue("@DateOfJoining", ed.DateOfJoining);
                cmd.Parameters.AddWithValue("@Designation", ed.Designation);
                cmd.Parameters.AddWithValue("@Degree", ed.Degree);
                cmd.Parameters.AddWithValue("@PassOutYear", ed.PassOutYear);

               
                cmd.ExecuteNonQuery();
                sda.Fill(dt);
            }
            return RedirectToAction("ListEmployeeDetails");
        }

        // GET: EmpDetailsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmpDetailsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Assessment/Controllers/newEmpController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using SampleProject.Models;
namespace SampleProject.Controllers
{
    public class newEmpController : Controller
    {
        SqlConnection con = new SqlConnection("Server = DESKTOP-OK1P17M\\MSSQLSERVERNEW; Database = EmployeeDB; integrated security =True");
        // GET: newEmpController
        [HttpGet]
        public ActionResult ListEmployee()
        {
            DataTable dt = new DataTable();
            using (con) {
                con.Open();
                SqlCommand cmd = new SqlCommand("SP_listEmployee", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                sda.Fill(dt);

            }
            return View(dt);
        }


        public ActionResult Create()
        {
            return View(new Employee());
        }

       
       [HttpPost]

        public ActionResult Create(Employee emp, Department dept)
        {
            DataTable dt = new DataTable();
            using (con)
            {

                con.Open();
                SqlCommand cmd = new SqlCommand("SP_InsertEmployee", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                //cmd.Parameters.AddWithValue("@Empid", ed.Empid);
                cmd.Parameters.AddWithValue("@Deptid", dept.Deptid);
                cmd.Parameters.AddWithValue("@EmpName", emp.EmpName);

    
              
                cmd.ExecuteNonQuery();
                sda.Fill(dt);
            }
            return RedirectToAction("ListEmployee");
        }

        //public ActionResult select()
        //{ }




        [HttpGet]
        public ActionResult EditEmployee()
        {
            return View(new Employee());
        }


            [HttpPost]

            public ActionResult EditEmployee(Employee e)
        {
            DataTable dt = new DataTable();
            using (con)
                {

                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_EDITEMP", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                   
                    cmd.Parameters.AddWithValue("@Deptid", e.Deptid);
                    cmd.Parameters.AddWithValue("@EmpName", e.EmpName);

            

                    cmd.ExecuteNonQuery();
                sda.Fill(dt);
            }
                return RedirectToAction("ListEmployee");
            }


            //// GET: newEmpController/Delete/5
            //public ActionResult Delete(int id)
            //{
            //    return View();
            //}

            //// POST: newEmpController/Delete/5
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public ActionResult Delete(int id, IFormCollection collection)
            //{
            //    try
            //    {
            //        return RedirectToAction(nameof(Index));
            //    }
            //    catch
            //    {
            //        return View();
            //    }

            // }
        

    }
}

Assessment/Views/newEmp/ListEmployee.cshtml
List of Employees

@model System.Data.DataTable
@{
    ViewBag.Title = "ListEmployee";

}
<table class="table table-bordered table-striped">
    <tr>
        <th> EmpNo</th>
        <th> EmpName</th>
        <th> DeptName</th>
    </tr>

    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>
                <a href="@Url.Action("ListEmployeeDetails", "EmpDetails", new { @id = @Model.Rows[i][0] })"> @Model.Rows[i][0]</a>
            </td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>
                <a href="@Url.Action("SelectEmp", "newEmp")">update </a> 

            </td>
        </tr>

    }
</table>
<a href=" @Url.Action("Create","newEmp")">Add Employee</a>
<br />
<a href=" @Url.Action("EditEmployee","newEmp")"> Update Employee</a>

Assessment/Views/newEmp/SelectEmp.cshtml
@model SampleProject.Models.Employee

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SelectEmp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpName" class="control-label"></label>
                <input asp-for="EmpName" class="form-control" />
                <span asp-validation-for="EmpName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deptid" class="control-label"></label>
                <input asp-for="Deptid" class="form-control" />
                <span asp-validation-for="Deptid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}