Controllers/BankController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using SampleProject.Models;
using SampleProject.Controllers;


namespace SampleProject.Controllers
{
    public class BankController : Controller
    {
        SqlConnection con = new SqlConnection("Server = DESKTOP-OK1P17M\\MSSQLSERVERNEW; Database = EmployeeDB; integrated security =True");
        [HttpGet]
        public ActionResult ListBankDetails()
        {
            DataTable dt = new DataTable();

            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_ShowBankDetails", con);


                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataReader sda = cmd.ExecuteReader();
                    dt.Load(sda);
                    
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return View(dt);
        }



        public ActionResult CreateBankDetails()
        {
            return View(new BankDetail());
        }

        [HttpPost]

        public ActionResult CreateBankDetails(BankDetail bd)
        {
            DataTable dt = new DataTable();
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_InsertBankDetails", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@Empid", bd.Empid);
                   ;
                    cmd.Parameters.AddWithValue("@BankName", bd.BankName);
                    cmd.Parameters.AddWithValue("@AccountNo", bd.AccountNo);
                    cmd.Parameters.AddWithValue("@BasicSalary", bd.BasicSalary);
                    cmd.Parameters.AddWithValue("@HRA", bd.HRA);
                    cmd.Parameters.AddWithValue("@OtherAllowances", bd.OtherAllowances);


                   

                    cmd.Parameters.AddWithValue("@PF", bd.PF);
                    cmd.Parameters.AddWithValue("@MedicalPremium", bd.MedicalPremium);
                    cmd.Parameters.AddWithValue("@TDS", bd.TDS);
                  
                    cmd.ExecuteNonQuery();
                    sda.Fill(dt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }
            }
            return RedirectToAction("ListBankDetails");
        }















        [HttpGet]
        public ActionResult EditBank(int id)
        {
            BankDetail bd = new BankDetail();
            DataTable dt = new DataTable();
            try
            {
                con.Open();
                SqlCommand cmd = new SqlCommand("BANKEDIT", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                sda.SelectCommand.Parameters.AddWithValue("@Bankid", id);
                sda.Fill(dt);
                if (dt.Rows.Count == 1)
                {



                    bd.Bankid = Convert.ToInt32(dt.Rows[0][0]);
                    
                        bd.BankName = dt.Rows[0][1].ToString();


                   bd.AccountNo = Convert.ToInt32(dt.Rows[0][2]);
                    bd.BasicSalary = Convert.ToInt32(dt.Rows[0][3]);
                    bd.HRA = Convert.ToInt32(dt.Rows[0][4]);
                    bd.OtherAllowances = Convert.ToInt32(dt.Rows[0][5]);
                   
                    bd.PF = Convert.ToInt32(dt.Rows[0][6]);
                    bd.MedicalPremium = Convert.ToInt32(dt.Rows[0][7]);
                    bd.TDS = Convert.ToInt32(dt.Rows[0][8]);



                    return View(bd);
                }
                else
                {

                    return RedirectToAction("EditBank");
                }


            }
            catch (Exception se)
            {
                return View();

            }



           // return View(new BankDetail());
        }


        [HttpPost]
   
        public ActionResult EditBank(BankDetail bd)
        {
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_EDITBANK", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@Empid", bd.Empid);
                    cmd.Parameters.AddWithValue("@BankName", bd.BankName);
                    cmd.Parameters.AddWithValue("@AccountNo", bd.AccountNo);
                    cmd.Parameters.AddWithValue("@BasicSalary", bd.BasicSalary);
                    cmd.Parameters.AddWithValue("@HRA", bd.HRA);
                    cmd.Parameters.AddWithValue("@OtherAllowances", bd.OtherAllowances);


                    cmd.Parameters.AddWithValue("@PF", bd.PF);
                    cmd.Parameters.AddWithValue("@MedicalPremium", bd.MedicalPremium);
                    cmd.Parameters.AddWithValue("@TDS", bd.TDS);



                    cmd.ExecuteNonQuery();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }
            }
            return RedirectToAction("ListBankDetails");
        }
      
        [HttpGet]

        public ActionResult DeleteBank(int id)
        {
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_Delete_Bank", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@Bankid", id);
                    cmd.ExecuteNonQuery();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }

            return RedirectToAction("ListBankDetails");
        }


        public ActionResult ShowNetSalary(int id)
        {
            DataTable dt = new DataTable();

            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("ShowNetSal", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@EmpDetailid", id);
                    sda.Fill(dt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return View(dt);
        }


        public ActionResult ShowGrossSalary(int id)
        {
            DataTable dt = new DataTable();

            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("ShowGross", con);


                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@EmpDetailid", id);
                    sda.Fill(dt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return View(dt);
        }



    }
}


Controllers/EmpDetailsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SampleProject.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace SampleProject.Controllers
{
    public class EmpDetailsController : Controller
    {
       

        SqlConnection con = new SqlConnection("Server = DESKTOP-OK1P17M\\MSSQLSERVERNEW; Database = EmployeeDB; integrated security =True");

        public ActionResult ListEmployeeDetails()
        {
            DataTable dt = new DataTable();
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_ListEmployeeDetail", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataReader sda = cmd.ExecuteReader();
                    dt.Load(sda);
                   
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return View(dt);
        }



        public ActionResult onclick(int id)
        {
            EmployeeDetail ed = new EmployeeDetail();
            DataTable dt = new DataTable();
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("onclick", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("Empid", id);
                   
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.ExecuteNonQuery();
                    sda.Fill(dt);
                   
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return View(dt);
        }



















        [HttpGet]
        public ActionResult CreateEmployeeDetail()
        {
            return View(new EmployeeDetail());
        }

       
        [HttpPost]

        public ActionResult CreateEmployeeDetail(EmployeeDetail ed)
        {
            DataTable dt = new DataTable();
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_CreateEmpDetail", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);

                    cmd.Parameters.AddWithValue("Empid", ed.Empid);
                    cmd.Parameters.AddWithValue("@DateOfBirth", ed.DateOfBirth);
                    cmd.Parameters.AddWithValue("@DateOfJoining", ed.DateOfJoining);
                    cmd.Parameters.AddWithValue("@Designation", ed.Designation);
                    cmd.Parameters.AddWithValue("@Degree", ed.Degree);
                    cmd.Parameters.AddWithValue("@PassOutYear", ed.PassOutYear);


                     cmd.ExecuteNonQuery();
                    sda.Fill(dt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }
            return RedirectToAction("ListEmployeeDetails");
        }








        [HttpGet]
       
        public ActionResult EditEMpDetail(int id)
        {
            EmployeeDetail ed = new EmployeeDetail();
            DataTable dt = new DataTable();
            try
         {
                con.Open();
                SqlCommand cmd = new SqlCommand("EMPDETSIL", con);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                sda.SelectCommand.Parameters.AddWithValue("@EmpDetailid", id);
                sda.Fill(dt);
                if (dt.Rows.Count == 1)
                {



                   ed.EmpDetailid= Convert.ToInt32(dt.Rows[0][0]);
             
                      ed.DateOfBirth =  Convert.ToString(dt.Rows[0][1]);
                  
                     ed.DateOfJoining = Convert.ToString(dt.Rows[0][2]);
                    ed.Designation = dt.Rows[0][3].ToString();
                    ed.Degree= dt.Rows[0][4].ToString();
                    ed.PassOutYear= dt.Rows[0][5].ToString();



                 
                    return View(ed);
                }
                else
                {

                    return RedirectToAction("EditEmployeeDetails");
                }


            } 
            catch (Exception se )
            {
                return View();

            }



           
        }

      
        [HttpPost]
      
        public ActionResult EditEmpDetail(EmployeeDetail ed)
        {
            DataTable dt = new DataTable();
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_EditEmpDetails", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);

                    cmd.Parameters.AddWithValue("Empid", ed.Empid);
                    cmd.Parameters.AddWithValue("@DateOfBirth", ed.DateOfBirth);
                    cmd.Parameters.AddWithValue("@DateOfJoining", ed.DateOfJoining);
                    cmd.Parameters.AddWithValue("@Designation", ed.Designation);
                    cmd.Parameters.AddWithValue("@Degree", ed.Degree);
                    cmd.Parameters.AddWithValue("@PassOutYear", ed.PassOutYear);


                    cmd.ExecuteNonQuery();
                    sda.Fill(dt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }
            }
            return RedirectToAction("ListEmployeeDetails");
        }

       

      
        [HttpGet]
       
        public ActionResult DeleteEmployeeDetails(int id)
        {
            using (con)
            {
                try
                {
                    con.Open();
                    SqlCommand cmd = new SqlCommand("SP_DeleteEmpDetail", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    cmd.Parameters.AddWithValue("@EmpDetailid", id);
                    cmd.ExecuteNonQuery();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }

            }

            return RedirectToAction("ListEmployeeDetails");

        }
      



    }
}

Views/Bank/CreateBankDetails.cshtml
@model SampleProject.Models.BankDetail

<h4>BankDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBankDetails">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountNo" class="control-label"></label>
                <input asp-for="AccountNo" class="form-control" />
                <span asp-validation-for="AccountNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasicSalary" class="control-label"></label>
                <input asp-for="BasicSalary" class="form-control" />
                <span asp-validation-for="BasicSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HRA" class="control-label"></label>
                <input asp-for="HRA" class="form-control" />
                <span asp-validation-for="HRA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OtherAllowances" class="control-label"></label>
                <input asp-for="OtherAllowances" class="form-control" />
                <span asp-validation-for="OtherAllowances" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PF" class="control-label"></label>
                <input asp-for="PF" class="form-control" />
                <span asp-validation-for="PF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicalPremium" class="control-label"></label>
                <input asp-for="MedicalPremium" class="form-control" />
                <span asp-validation-for="MedicalPremium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TDS" class="control-label"></label>
                <input asp-for="TDS" class="form-control" />
                <span asp-validation-for="TDS" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListBankDetails">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

Views/Bank/EditBank.cshtml
@model SampleProject.Models.BankDetail

<h4>BankDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBank">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Bankid" class="control-label"></label>
                <input asp-for="Bankid" class="form-control" />
                <span asp-validation-for="Bankid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountNo" class="control-label"></label>
                <input asp-for="AccountNo" class="form-control" />
                <span asp-validation-for="AccountNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasicSalary" class="control-label"></label>
                <input asp-for="BasicSalary" class="form-control" />
                <span asp-validation-for="BasicSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HRA" class="control-label"></label>
                <input asp-for="HRA" class="form-control" />
                <span asp-validation-for="HRA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OtherAllowances" class="control-label"></label>
                <input asp-for="OtherAllowances" class="form-control" />
                <span asp-validation-for="OtherAllowances" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PF" class="control-label"></label>
                <input asp-for="PF" class="form-control" />
                <span asp-validation-for="PF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicalPremium" class="control-label"></label>
                <input asp-for="MedicalPremium" class="form-control" />
                <span asp-validation-for="MedicalPremium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TDS" class="control-label"></label>
                <input asp-for="TDS" class="form-control" />
                <span asp-validation-for="TDS" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action=""ListBankDetails">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bank/ListBankDetails.cshtml
Bank Details

@model System.Data.DataTable
@{
    ViewBag.Title = "ListBankDetails";

}
<table class="table table-bordered table-striped">
    <tr>
        <th>Bankid</th>
        <th>EmpName </th>
        <th>DeptName </th>
        <th>BankName </th>
        <th>AccountNo </th>
        <th>BasicSalary</th>
        <th>HRA</th>
        <th>OtherAllowances</th>
        <th>GrossSalary</th>
        <th>Pf</th>
        <th>MedicalPremium</th>
        <th>TDS</th>
        <th>NetSalary</th>



    </tr>


    @for (int i = 0; i < Model.Rows.Count; i++)
    {
<tr>

    <td>@Model.Rows[i][0]</td>
    <td>@Model.Rows[i][1]</td>
    <td>@Model.Rows[i][2]</td>
    <td>@Model.Rows[i][3]</td>
    <td>@Model.Rows[i][4]</td>
    <td>@Model.Rows[i][5]</td>
    <td>@Model.Rows[i][6]</td>
    <td>@Model.Rows[i][7]</td>
    <td>@Model.Rows[i][8]</td>
    @*<td> <a href="@Url.Action("Gross","Bank", new { @id = @Model.Rows[i][0] })"> @Model.Rows[i][8]</a></td>*@
    <td>@Model.Rows[i][9]</td>
    <td>@Model.Rows[i][10]</td>
    <td>@Model.Rows[i][11]</td>
    <td>@Model.Rows[i][12]</td>

    <td>
        <a href="@Url.Action("DeleteBank","Bank",new { @id = @Model.Rows[i][0]})">Delete</a>

    </td>
    <td>
        <a href="@Url.Action("EditBank","Bank",new { @id = @Model.Rows[i][0]})">Edit</a>

    </td>

</tr>

    }
</table>
<a href=" @Url.Action("CreateBankDetails","Bank")">Add Bank Detail</a>
@*<br />
<a href=" @Url.Action("EditBank","Bank")">Edit Bank Detail</a>
<br />*@
@*<a href=" @Url.Action("DeleteBank","Bank")">Delete Bank Detail</a>
<a href=" @Url.Action("Gross","Bank")">cal gross salary</a>*@


Views/Bank/ShowGrossSalary.cshtml
List of Employees

@model System.Data.DataTable
@{
    ViewBag.Title = "ShowGrossSalary";

}
<table class="table table-bordered table-striped">
    <tr>
        <th> EmpName</th>
        <th> BasicSalary</th>
        <th> HRA</th>
        <th>
        OtherAlloawances</th>
        
        <th>GrossSalary</th>
    </tr>

    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>
            <td>@Model.Rows[i][4]</td>
          


        </tr>

    }
</table>
<br />
<a href=" @Url.Action("ListEmployeeDetails","EmpDetails")"> BACK_TO_EMPLOYEE_DETAILS</a>

Views/Bank/ShowNetSalary.cshtml
List of Employees

@model System.Data.DataTable
@{
    ViewBag.Title = "ShowNetSalary";

}
<table class="table table-bordered table-striped">
    <tr>
        <th> EmpName</th>
        <th> Grosssalary</th>
        <th> PF</th>
        <th> MedicalPremium</th>
        <th> TDS</th>
        <th>NetSalary</th>
    </tr>

    @for (int i = 0; i < Model.Rows.Count; i++)
    {
<tr>
    <td>@Model.Rows[i][0]</td>
    <td>@Model.Rows[i][1]</td>
    <td>@Model.Rows[i][2]</td>
    <td>@Model.Rows[i][3]</td>
    <td>@Model.Rows[i][4]</td>
    <td>@Model.Rows[i][5]</td>



</tr>

    }
</table>
<br />
<a href=" @Url.Action("ListEmployeeDetails","EmpDetails")"> BACK_TO_EMPLOYEE_DETAILS</a>